---
- name: install default-jdk
  hosts: db
  become: yes

  tasks:
    - name: Ensure default-jdk packege is present
      apt:
        name: default-jdk
        state: present

- name: install git
  hosts: db
  become: yes

  tasks:
    - name: Ensure git packege is present
      apt:
        name: git
        state: present
    - name: downloading repo
      command: "git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git"
      become: yes

- name: install maven
  hosts: db
  become: yes

  tasks:
  - name: Ensure maven packege is present
    apt:
     name: maven
     state: present

  - name: running build
    command: mvn package
    become: yes
    args:
      chdir: boxfuse-sample-java-war-hello/

  - name: copy builded package to local
    fetch:
      src: /root/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /home/ubuntu/1/
      flat: yes

- name: install default-jre
  hosts: wed
  become: yes

  tasks:
    - name: Ensure default-jre packege is present
      apt:
        name: default-jre
        state: present

- name: install tomcat9
  hosts: web
  become: yes

  tasks:
  - name: Ensure tomcat package is present
    apt:
     name: tomcat9
     state: present

  - name: Ensure hello-1.0.war is present
    copy:
     src: /home/ubuntu/1/hello-1.0.war
     dest: /var/lib/tomcat9/webapps/

  - name: Ensure that tomcat is running
    service:
     name: tomcat9
     state: started
